packageExtensions:
  eslint-plugin-unicorn@*:
    dependencies:
      eslint-visitor-keys: '*'
  typescript-eslint-language-service@*:
    dependencies:
      '@typescript-eslint/typescript-estree': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.cjs
