yarnPath: '.yarn/releases/yarn-berry.cjs'
packageExtensions:
  'eslint-plugin-unicorn@*':
    dependencies:
      'eslint-visitor-keys': '*'
  'typescript-eslint-language-service@*':
    dependencies:
      '@typescript-eslint/typescript-estree': '*'
